### ISSUE TITLE
Demo code doesn't seem to work on Xcode 11.5 and iOS 13.5

### ISSUE THREAD

**Issue by spsonore** [cloud-annotations/object-detection-ios#3]
Hi, was trying to follow the demo outlined in https://cloud.annotations.ai/workshops/object-detection/index.html.
I created a model on https://cloud.annotations.ai from a video (.mov) file I made of a green tea bottle (~30s....about 60 images after uploading to IBM cloud)
But when I tried to run the iOS code on my iPhone, the app showed multiple boxes of empty outlines right away.
![App_empty_outlines](https://user-images.githubusercontent.com/67399150/85641851-a32eb500-b644-11ea-8e3f-a9f52efcaa46.jpg)

I'm running on Xcode 11.5 and iOS 13.5.   
Has this code been attempted on these versions? 

![image](https://user-images.githubusercontent.com/67399150/85641925-d40eea00-b644-11ea-9d2b-eb8a93f4450c.png)

![image](https://user-images.githubusercontent.com/67399150/85641983-f43ea900-b644-11ea-9e05-33dca3dd70c3.png)

**Comment by bourdakos1** [comment]
It looks like it’s working, I think you just need better training data

**Comment by spsonore** [comment]
I tried adding more images to my model.  It's up to 151 images now (demo indicated only 50 images were needed).  But after retraining and rebuilding the app with the new model, I still see the same results.   I tried pointing the camera to both completely black and white surfaces and I still see those phantom bounding boxes being drawn.  I had assumed the boxes wouldn't show up in those situations since for all the images, I only drew bounding boxes on the green bottle.  So if there is no green object in the camera's view, I assume, there should be no bounding boxes being drawn/triggered. 

![image](https://user-images.githubusercontent.com/67399150/85758260-02cca500-b6c5-11ea-97e7-dc072536cae6.png)

**Comment by bourdakos1** [comment]
quantity does not make up for poor quality. from your screenshot it looks like all the photos are very similar. You need more photos in different conditions, different backgrounds, lighting etc...

**Comment by spsonore** [comment]
Alright thanks for the suggestion.  The new images I uploaded were of the bottle in a different location.  
I'm going to try out IBM Visual Insights free trial....looks like there are additional tools in that interface to create new datasets automatically out of existing images.
